services:
  backend:
    build: ./backend
    environment:
      - DATA_DIR=/data
    volumes:
      - ./data:/data
    ports:
      - "5171:5171"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5172:5172"
